apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: voting-app
    tier: backend
spec:
  containers:
    -  name: redis-container
       image: postgres:9.4
       ports:
         - containerPort: 5432
       env:
         -  name:  POSTGRES_USER
            value: "postgres"
         -  name: POSTGRES_PASSWORD
            value: "postgres"