apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: voting-app
    tier: frontend
spec:
  type: NodePort
  ports:
    targetPort: 80
    port: 80
    nodePort: 69691


  selector:
    name: result-pod
    app: voting-app
    tier: frontend