apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    name: vote
    app: voting-app
    tier: frontend
spec:
  containers:
    -  name: vote-container
       image: akli1512/example-voting-app_vote:v1
       ports:
         - containerPort: 80


