apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote-service
    app: voting-app
    tier: frontend
spec:
  type: NodePort
  ports:
    targetPort: 80
    port: 80
    nodePort: 69690


  selector:
    name: vote-pod
    app: voting-app
    tier: frontend