apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    name: worker
    app: voting-app
    tier: backend

spec:
  containers:
    -  name: worker-container
       image: akli1512/example-voting-app_worker:v1
